<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace hrzg\filefly\models\base;

use Yii;

/**
 * This is the base-model class for table "filefly_hashmap".
 *
 * @property integer $id
 * @property string $component
 * @property string $path
 * @property integer $access_owner
 * @property string $access_read
 * @property string $access_update
 * @property string $access_delete
 * @property string $created_at
 * @property string $updated_at
 */
abstract class FileflyHashmap extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'filefly_hashmap';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['component', 'path'], 'required'],
            [['access_owner'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['component'], 'string', 'max' => 45],
            [['path'], 'string', 'max' => 745],
            [['access_read', 'access_update', 'access_delete'], 'string', 'max' => 255],
            [
                ['component', 'path', 'access_owner'],
                'unique',
                'targetAttribute' => ['component', 'path'],
                'message'         => 'The combination of Component, Path has already been taken.'
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'            => Yii::t('filefly', 'ID'),
            'component'     => Yii::t('filefly', 'Component'),
            'path'          => Yii::t('filefly', 'Path'),
            'access_owner'  => Yii::t('filefly', 'Access Owner'),
            'access_read'   => Yii::t('filefly', 'Access Read'),
            'access_update' => Yii::t('filefly', 'Access Update'),
            'access_delete' => Yii::t('filefly', 'Access Delete'),
            'created_at'    => Yii::t('filefly', 'Created At'),
            'updated_at'    => Yii::t('filefly', 'Updated At'),
        ];
    }
}
